spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookmoa
    username: bookmoa
    password: bookmoa1234

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: bookmoa
    password: bookmoa1234

aladin:
  api:
    key: ${ALADIN_API_KEY}
    base-url: http://www.aladin.co.kr/ttb/api/

server:
  port:8080